on:
  push:

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        files:
          - { name: 1111 }
          - { name: 2222 }
          - { name: 3333 }
    steps:
      - run: touch ${{ matrix.files.name }}
      - uses: actions/upload-artifact@v3
        with:
          name: aaa_${{ matrix.files.name }}
          path: ${{ matrix.files.name }}
  
  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -l